name: CI DevSecOps - Workflow
on:
  push:
    branches:
      - bran-secops-lab

jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: 1RA PRUEBA
      #   run: |
      #     echo "TEST PRUEBA"
      - name: Validar Creación de Proyecto en SonarCloud
        id: validateProjectOnSonar
        run: |
          set +e
          curl -f -X POST -u '${{ secrets.TOKEN_SONAR }}:' 'https://sonarcloud.io/api/projects/create' \
            -d 'name=${{ github.event.repository.name }}' \
            -d 'project=${{ github.event.repository.name }}' \
            -d 'organization=curso-secops' \
            -d 'visibility=public'

          if [ $? -ne 0 ]; then
            echo "Proyecto ya existe en Sonar."
          else
            echo "Proyecto creado exitosamente en Sonar."

            echo "Se establece rama como main por defecto."
            curl -X POST -u '${{ secrets.TOKEN_SONAR }}:' 'https://sonarcloud.io/api/project_branches/rename' \
              -d 'name=main' \
              -d 'project=${{ github.event.repository.name }}'
          fi
          set -e

      - name: Ejecutar Analisis SAST
        uses: SonarSource/sonarcloud-github-action@v2.2.1
        with:
          organization: curso-secops
          projectKey: ${{ github.event.repository.name }}
          projectName: ${{ github.event.repository.name }}
        env:
          SONAR_TOKEN: ${{ secrets.TOKEN_SONAR }}

      - name: Validando Resultados SAST
        run: |
          issueValidate=$(curl -s -X GET -u '${{ secrets.TOKEN_SONAR }}:' \
            'https://sonarcloud.io/api/issues/search?branch=main&componentKeys=${{ github.event.repository.name }}-curso-secops&facets=severities' \
            | jq '.facets[0].values[1].count')

            echo "Cantidad de issues bloqueantes: $issueValidate"

          if [ "$issueValidate" -gt 0 ]; then
            echo "Se encontraron issues vulnerables."
            #exit 1
          else
            echo "No se encontraron issues vulnerables."
          fi

  # SCA:
  #   runs-on: ubuntu-latest
  #   needs: SAST
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Instalar Dependencias Check
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install -y unzip
  #         wget https://github.com/jeremylong/DependencyCheck/releases/download/v10.0.2/dependency-check-10.0.2-release.zip
  #         unzip dependency-check-10.0.2-release.zip -d dependency-check
  #         chmod +x dependency-check/bin/dependency-check.sh
